get http://localhost:3007/api/word_game?sentence=sentences are the worst


###

post http://localhost:3007/api/phonebill/total
Content-Type: application/json

{
    "bill": "call,sms,call"
}


get http://localhost:3007/api/phonebill/prices
# Content-Type: application/json

# {
#     "prices": "call,sms,call"
# }


post http://localhost:3007/api/enough
Content-Type: application/json

{
    "bill": "call,sms,call"
}

###

post http://localhost:3007/api/enough
Content-Type: application/json

{
    "usage": "call,sms,call",
    "available": 70,
}